### PR TITLE
Adding grunt and splitting up styles

### PR DESCRIPTION
**Pull request by jamesmacfie**
Two parts to this pull request:
- I've added in [Grunt](http://gruntjs.com/) as a task runner to take care of building our CSS, minifying our JS etc. At the moment all it does is build the CSS but as we develop more of the front end I'll be using this to do as much of the hard work as I can.
- Most of this pull request is splitting up `calendar.scss` into multiple files, each dealing with a certain aspect of the styles. I simply wanted to first get a few things in order and not change any of the existing CSS before I start a bit of refactoring (most of the CSS here can be improved, no offence to whoever wrote it).  I'll also start to put in a few comments etc in there as well so that other devs can see what's happening (I don't even know what some of the styles do, for example). If I change any markup then I'll run it by @jasonkiss to make sure that it's as accessible as it needs to be etc.

### CODE REVIEW

**Comment by Aupajo** [comment]
Awesome! Is there any reason to use Grunt beyond minification/concatenation of CSS/JS? Because that's already built-in.

**Comment by davekeyes** [comment]
Heya ... let me know if/when there is something for me to look at :) Chur.

**Comment by jamesmacfie** [comment]
@aupajo I'm using watch to watch for file changes to initiate a Sass build - important as I split up the styles into their own modules etc. I'll continue to leave the minification out then

**Comment by Aupajo** [comment]
Asset compilation happens on-the-fly – as requests are made. No need to have a separate process unless you want to.

**Comment by Aupajo** [comment]
Like, if you create `stylesheets/some_style.scss`, Almanack will respond to a request for `/stylesheets/some_style.css` with the rendered CSS.

**Comment by jamesmacfie** [comment]
So, if I have style.scss which imports _variables.scss, _base.scss, _layout.scss plus a bunch of other Sass partials, Almanack will know to only generate style.css which will include all those other files?

**Comment by jamesmacfie** [comment]
Because I think if that's the case, we won't need grunt. I can just use `sass watch` for local dev. And I'm doubtful there'll any sort of javascript file magic that we'll need a build tool for

**Comment by Aupajo** [comment]
You should be able to use `@import`, as in:

```
@import 'variables';
@import 'base';
```

Not sure if you need the underscore.

**Comment by fourseven** [comment]
Jumping in re: the underscore - sass treats files which start with underscores as partials and will only process them when they're included, and not individually. So, like Rails - you should never use the underscore when referencing these files. If they don't exist as a separate file, they should be partials/underscored.

**Comment by jamesmacfie** [comment]
Closing this as I've got some other stuff that I'll need people's opinions on first

**Pull request closed without merging**
